### ISSUE TITLE
Integration inside of Chat UI

### ISSUE THREAD

**Issue by SalahAdDin** [flyerhq/flutter_link_previewer#21]
Hi,

I think i saw a way to integrate this previewer on the Chat UI, but i couldn't remembere when or how.

Is there any officla tutorial about it?

Thank you.

**Comment by demchenkoalex** [comment]
Hi @SalahAdDin if you are talking about `flutter_chat_ui` it works automatically there, already integrated, since it is our package too. If you are talking about any other chat UI I guess documentation here is sufficient or you can take a look how we integrated it inside `flutter_chat_ui` repo. Does this answer your question?

**Comment by SalahAdDin** [comment]
> Hi @SalahAdDin if you are talking about `flutter_chat_ui` it works automatically there, already integrated, since it is our package too. If you are talking about any other chat UI I guess documentation here is sufficient or you can take a look how we integrated it inside `flutter_chat_ui` repo. Does this answer your question?

Yeah, i was talking about `flutter_chat_ui`, yeah!

**Comment by demchenkoalex** [comment]
As I said, it is already there. Anything else?
